### ISSUE TITLE
feature_request(tables): support tables without thead

### ISSUE THREAD

**Issue by Kristinita** [ryanwellsdotcom/jquery.responsive-tables#3]
### 1. Summary

**If** `table` haven't `thead` tag, `tbody` solely:

    it would be nice, if jquery-responsive-table automatically detect it and create one-column table for small screens.

### 2. Argumentation

In some my web-pages, where I have multiple one-type tables, I don't use `thead`, because it duplicates.

### 3. Data

For example, I have a simple table:

```text
А1 |A2
B1 |B2
```

+ [**Sources on Codepen**](https://codepen.io/Kristinita/pen/YoQyvK):

```html
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-responsive-tables/js/jquery.responsive-tables.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-responsive-tables/css/responsive-tables.min.css" />
<table>
    <tbody>
        <tr>
            <td>A1</td>
            <td>A2</td>
        </tr>
        <tr>
            <td>B1</td>
            <td>B2</td>
        </tr>
    </tbody>
</table>
```

```stylus
body
    font-size 4rem

table
    width 100%

```

```coffee
$(document).ready ->
    $.responsiveTables()
    return
```

### 4. Expected behavior

```text
А1
A2
B1
B2
```

![expected table](https://i.imgur.com/Z9rHBIC.png)

### 5. Actual behavior

Empty space in left part of web page:

```text
   |А1
   |A2
   |B1
   |B2
```

+ [**Live demo on Codepen**](https://codepen.io/Kristinita/full/YoQyvK)

![non-expected table](https://i.imgur.com/lX8262B.png)

Part of my real table:

![real table](https://i.imgur.com/unD7YBZ.png)

Thanks.

**Comment by ryanwellsdotcom** [comment]
Извините за задержку

I've updated the solution to allow for the exclusion of the <thead> element. Be sure to swap out both the CSS and JavaScript files.

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark:

Minimal example — [**live demo on Codepen**](https://cdpn.io/Kristinita/fullpage/YoQyvK) from my issue.

Thanks.
